substitutions:
  name: sonoff-m5-1-gang
  friendly_name: Sonoff SwitchMan M5 1-gang

esphome:
  name: $name
  name_add_mac_suffix: true
  project:
    name: sonoff.switchman-m5-1-gang
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ap: {}

dashboard_import:
  package_import_url: github://jesserockz/sonoff-configs/sonoff-switchman-m5-1-gang.yaml@main

improv_serial:

button:
  - platform: restart
    id: restart_button
    name: ${friendly_name} Restart

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime
    disabled_by_default: true

binary_sensor:
  - platform: status
    name: ${friendly_name} Status

  - platform: gpio
    name: ${friendly_name}
    disabled_by_default: true
    pin:
      number: 0
      inverted: true
    on_multi_click:
      - timing:
          - ON for 50ms to 350ms
          - OFF for at least 50ms
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 5s
        then:
          - button.press: restart_button

switch:
  - platform: gpio
    name: Relay
    id: relay
    pin:
      number: 19

output:
  - platform: ledc
    pin: 18
    id: button_backlight

light:
  - platform: status_led
    pin:
      number: 5
      inverted: true
    id: status_light

  - platform: monochromatic
    name: ${friendly_name} Button Backlight
    output: button_backlight
    entity_category: config
