name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-m5-3-gang:
    name: Publish M5 3-gang
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: sonoff-switchman-m5-3-gang.yaml
      name: SwitchMan M5 3-gang
      manifest_filename: switchman-m5-3-gang-manifest.json
      clean: false


  publish-m5-1-gang:
    name: Publish M5 1-gang
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: sonoff-switchman-m5-1-gang.yaml
      name: SwitchMan M5 1-gang
      manifest_filename: switchman-m5-1-gang-manifest.json
      clean: false
