name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@multiple-builds
    with:
      files: sonoff-switchman-m5-3-gang.yaml
      name: SwitchMan M5 3-gang
      manifest_filename: switchman-m5-3-gang-manifest.json
      clean: false
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
